version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bnovo
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./bnovo.sql:/docker-entrypoint-initdb.d/bnovo.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
